<?php
session_start();
include("../config/db.php");

if (!isset($_SESSION["user_id"])) {
    header("Location: ../authentication/login.php");
    exit;
}

$user_id = (int)$_SESSION["user_id"];
$cert_id = isset($_GET['id']) ? (int)$_GET['id'] : 0;

$query = "SELECT c.*, t.title, u.first_name, u.last_name, 
                 t.date_submitted, t.status
          FROM certificates_table c
          JOIN thesis_table t ON c.thesis_id = t.thesis_id
          JOIN user_table u ON c.student_id = u.user_id
          WHERE c.certificate_id = ? AND c.student_id = ?";
$stmt = $conn->prepare($query);
$stmt->bind_param("ii", $cert_id, $user_id);
$stmt->execute();
$cert = $stmt->get_result()->fetch_assoc();
$stmt->close();

if (!$cert) {
    header("Location: projects.php?error=invalid_certificate");
    exit;
}

$updateQuery = "UPDATE certificates_table SET downloaded_count = downloaded_count + 1 WHERE certificate_id = ?";
$stmt = $conn->prepare($updateQuery);
$stmt->bind_param("i", $cert_id);
$stmt->execute();
$stmt->close();

$pageTitle = "Thesis Certificate";
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= htmlspecialchars($pageTitle) ?> - Theses Archiving System</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="stylesheet" href="css/certificate.css">
</head>
<body>
    <div class="certificate-wrapper">
        <div class="certificate">
            <div class="header">
                <h1>Certificate of Approval</h1>
                <h2>Thesis Archiving System</h2>
            </div>
            <div class="content">
                <p>This is to certify that</p>
                <div class="student-name"><?= htmlspecialchars($cert['first_name'] . ' ' . $cert['last_name']) ?></div>
                <p>has successfully completed and defended the thesis entitled</p>
                <div class="thesis-title">"<?= htmlspecialchars($cert['title']) ?>"</div>
                <p>on this day, <strong><?= date('F d, Y', strtotime($cert['generated_date'])) ?></strong></p>
                <p>and is hereby granted the approval for thesis submission.</p>
            </div>
            <div class="signature">
                <div class="signature-item">
                    <div class="signature-line"></div>
                    <p><strong>Thesis Adviser</strong></p>
                    <p>Faculty, Graduate School</p>
                </div>
                <div class="signature-item">
                    <div class="signature-line"></div>
                    <p><strong>Dean</strong></p>
                    <p>Graduate School</p>
                </div>
            </div>
            <div class="seal">
                <p>OFFICIAL<br>SEAL</p>
            </div>
            <div class="footer">
                <p>This certificate is automatically generated by Theses Archiving System</p>
                <p>Certificate ID: CERT-<?= str_pad($cert['certificate_id'], 6, '0', STR_PAD_LEFT) ?></p>
                <p>Downloaded: <?= $cert['downloaded_count'] ?> times</p>
            </div>
        </div>
        <div class="actions">
            <button onclick="window.print()" class="btn-print">
                <i class="fas fa-print"></i> Print Certificate
            </button>
        </div>
        <div style="text-align: center;">
            <a href="projects.php" class="back-link">
                <i class="fas fa-arrow-left"></i> Back to Projects
            </a>
        </div>
    </div>
    <script src="js/certificate.js"></script>
</body>
</html>